# Generated by Django 4.2.19 on 2025-02-20 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='gif',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
