# Generated by Django 4.2.19 on 2025-02-20 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0003_advertisement_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='transcript',
            field=models.CharField(default='exit', max_length=255),
            preserve_default=False,
        ),
    ]
