# Generated by Django 4.2.19 on 2025-02-20 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0004_video_transcript'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='transcript',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
