# Generated by Django 4.2.19 on 2025-02-20 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0005_alter_video_transcript'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='transcript',
        ),
    ]
