# Generated by Django 4.2.19 on 2025-02-20 19:44

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0007_youtubevideo_delete_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubevideo',
            name='video_url',
            field=embed_video.fields.EmbedVideoField(),
        ),
    ]
